#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'hostsfile'
cookbook 'nginx'
cookbook 'memcached'
cookbook 'postgresql'
cookbook 'git'
cookbook 'runit'
cookbook 'npm'
cookbook 'nginx'
cookbook 'gunicorn'
cookbook 'supervisor'