default["django_app"]["name"] = "pari"
default["django_app"]["debug"] = ""
default["django_app"]["settings_module"] = "prod" 
default["django_app"]["source_path"] = "/pari" 
default["django_app"]["server_name"] = "www.ruralindiaonline.org"
default["django_app"]["secret_key"] = "etkg=2eey_z6u*3ab9s&thcem(5s9w44s5ma0a12+pvpzs^5mk"
